spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xp997/hello-spring-cloud/tree/master/spring-cloud-config/
          search-paths: respo
          username:1096150741@qq.com
          password:1096150741peng

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/